In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!pip3 install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 4.2 MB 6.8 MB/s 
     |████████████████████████████████| 6.6 MB 2.1 MB/s 
     |████████████████████████████████| 86 kB 4.9 MB/s 
     |████████████████████████████████| 596 kB 56.7 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [ ]:
from transformers import BertTokenizerFast, GPT2LMHeadModel

model = GPT2LMHeadModel.from_pretrained('/content/drive/MyDrive/model_save(v2 6epoch까지학습)')

tokenizer = BertTokenizerFast.from_pretrained('/content/drive/MyDrive/model_save(v2 6epoch까지학습)')
input_ids = tokenizer.encode("text to tokenize")[1:]  # CLS token 제거

In [ ]:
import torch
tokenizer_gpt3 = BertTokenizerFast.from_pretrained("kykim/gpt3-kor-small_based_on_gpt2", 
                                                   bos_token='<|startoftext|>', 
                                                   eos_token='<|endoftext|>', 
                                                   pad_token='<|pad|>')
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

Downloading:   0%|          | 0.00/82.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/336k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/615 [00:00<?, ?B/s]

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'GPT2Tokenizer'. 
The class this function is called from is 'BertTokenizer'.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'GPT2Tokenizer'. 
The class this function is called from is 'BertTokenizerFast'.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [ ]:
model.eval()

def coverletter_generator(text):
  prompt = f"<|startoftext|> {text}"
  generated = torch.tensor(tokenizer_gpt3.encode(prompt)[1:]).unsqueeze(0)
  generated = generated.to(device)

  print(generated)

  sample_outputs = model.generate(
                                  generated, 
                                  do_sample=True,   
                                  top_k=50, 
                                  max_length = 500,
                                  top_p=0.95, 
                                  num_return_sequences=3,
                                  repetition_penalty=1.1
                                  )

  for i, sample_output in enumerate(sample_outputs):
    result = "{}: {}\n\n".format(i, tokenizer_gpt3.decode(sample_output, skip_special_tokens=True))
    print(result)
  return

In [ ]:
coverletter_generator('저의 강점은 ')

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


tensor([[42000, 16972, 38964,  8078,     3]])
0: 저의 강점은 수출을 이끄는 글로벌 인재가 되겠습니다. 기업 경영의 중요한 역할은 커뮤니케이션입니다. 소통과 협업으로 세계시장을 선도하는 가 될 것입니다. 는 수출입 기업의 물류 운송 유통 채널을 통해 국내 중소기업 협력 및 동반성장을 도모하기 때문입니다. 저는 이를 위해 년 개월간 코리아의 해외진출 파트너십 담당으로 참가했습니다. 제가 일하는 회사와 제품에 대해 이해시키고 지속적인 피드백을 공유하여 해외시장 진출에 이바지하고자 노력했습니다. 특히 코로나로부터 가장 민감한 을 활용해 물품 출고 및 출고를 진행했습니다. 또한 코로나로 인해 긴급 주문물량이 부족하여 현지 담당자와 실시간으로 연락하면서 물품을 준비했습 니다. 그 결과 기존 대비배의 수출 실적을 기록할 수 있었습니다. 에서 최고의 를 바탕으로 기업의 가치를 높이는 데 기여하겠습니다. 제가 가진 소통능력을 발휘해 가세계 시장을 선도하는 기업가이 되는 길에 함께 하겠습니다.. 본인의 지원 직무를 위해 필요한 핵심역량은 무엇인지 서술하고 남들과 차별화되는 본인만의 경쟁력은 무엇인지 기술하시오. 무역업 이해를 바탕으로 한 전략수립 능력 무역 전공을 통해 국내외 시장을 이해하고 분석하는 능력을 키웠습니다. 국제무역사와 무역영어 자격증을 취득함으로써 무역분야의 이론적 지식을 쌓았습니다. 국제물류관리사 자격 취득과 무역영어 급을 취득해 기본적인 무역지식을 습득했습니다. 더 나아가 통관 및 통관관리 무역영어급 자격증을 취득함으로써 무역업무 전반에 대한 이해를 넓혔습니다. 글로벌 공급망 관리와 고객만족 관리에 능한 로써 고객지향 마인드를 갖췄습니다. 또한 고객만족을 실현하기 위해서는 지속적인 소통이 중요하다고 생각합니 다. 국제교류 사교모임에서 꾸준히 영어공부를 해왔으며 교환학생을 갔을 때 다양한 인종종교문화를 직접 체험하며 문화권의 사람들을 만나기 위해 노력 했습니다. 저는 어학능력이 부족해 제외국어로 대화를 시도해야 하는 상황이

In [ ]:
coverletter_generator('저는 자료를 분석하는 능력이 강합니다. ')

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


tensor([[42000, 14156, 21992, 15626, 13975, 21561,  2122, 14015,  2016,     3]])
0: 저는 자료를 분석하는 능력이 강합니다. 여기서 제가 하게 된 분석력입니다. 특히 데이터 분석 과정에서 팀장으로서 데이터 분석이 원활하게 진행될 수 있도록 돕기 위해 자료 분석을 시행했습니다. 결과적으로 좋은 성적을 거두었고 이러한 분석에 따라 학교 홍보도우미 활동을 성공적으로 해낼 수 있었습니다. 이를 통해 분석력을 기를 수 있었고 좋은 결과를 얻을 수 있었습니다. 또한 업무 수행에 있어 데이터 분석에 있어 의사소통을 잘해야 한다고 생각합니다. 저는 학창시절부터 사람들과의사소통을 잘했습니다. 그 결과로 타인을 만나는데 거부감이 없습니다. 그 덕분에 많은 사람들이 저를 인간관계의 중심에 있는 사람으로 인식하고 있고 이러한 신뢰관계를 통해 원활한 대인관계를 이어오고 있습니다. 저의 이런 의사소통 능력은 한국도로공사에서도 도움이 될 것이라고 생각합니다. 입사 후에 어떤 일을 하든지 조직에서 문제가 발생한다면 적극적으로 소통을 하고 해결하기 위해 노력하겠습니다.. 이처럼 다양한 업무를 처리해야 하는 업무에도 동료들과 힘을 합쳐 빠르게 적응을 하겠습니다.. 본인이 지원한 분야에서 전문성을 발휘하기 위해 다른 사람과 협업할 때 더 나은 결과를 창출할 수 있다는 것을 깨닫고 이에 대한 기여도를 잊지 않도록 노력하겠습니다. 직무를 맡았을 때 필요한 지식이나 기술들을 알고 있어야 합니다. 또한 관련 지식을 익혀야 하기 때문에 이전에 어떤 부분을 준비해야 하는지 공부한 것과 더불어 현재 하고 있는 활동들을 좀 더 발전시킬 수 있는 부분에도 신경 써서 진행해야 할 것입니다. 이러한 업무는 혼자만으로는 해결하기 힘든 일이 있을 것이고 그에 따른 시행착오와 어려움들이 있을 것으로 생각합니다. 그러므로 이를 방지하기 위해 제가 먼저 다가가는 노력을 계속해 나가겠습니다.


1: 저는 자료를 분석하는 능력이 강합니다. 여기서 더 성장하고자

In [ ]:
coverletter_generator('저는 수학을 ')

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


tensor([[42000, 14156, 18846,  8051,     3]])
0: 저는 수학을 초등학교 중학교 시절 저에겐 영어 공포를 갖게 했습니다. 왜냐하면 과학 선생님이셨던 어머니께서는 제 게 영어를 가르치기 위해 년에 한 번씩 수능을 보셨습니다. 그런데 그것이 제가 영어를 전혀 모르던 어린 저에게는 굉장히 큰 도전이었습니다. 그러나 어머니는 제가 하는 공부를 보시고는 저한테 문제풀이를 많이 시키셨고 그 문제를 맞히는 사람이 나 기 시작했습니다. 그런데 어느 날 집에 돌아오면 제 인생에서 처음으로 저에게 화를 낸 친구가 선생님을 갑자기 부르게 되었습니다. 고등학교 학년 때 문과였던 친구가 실수로 수학 과목을 잘 듣지 못했기 때문에 일어난 일이었습니다. 저는 다시 일어선 다고 생각했지만 선생님은 저에게 계속 화를 내셨습니다. 저는 재수생활을 하게 되면 남들보다 더 열심히 공부하겠다고 다짐했고 저는 친구와 함께 문제를 풀고 문제들을 풀면서 점점 마음을 열었습니다. 그 덕분에 원하는 대학교에 진학하게 되었습니다. 또한 수능 이후 부족한 과목 공부도 다시 하게 되었고 이 계기로 더 영어에 대한 흥미를 가지게 되었습니다. 하지만 이 위기를 통해 저 자신이 우물안 개구리였다는 것을 깨닫게 되어 이후로는 다른 사람보다 더 많은 시간을 투자하여 목표를 이루기 위해 노력하고 있습니다. 그 이후로 다른 사람과 같이 일하면서 저는 사람들과 의견을 공유할 수 있는 토론과 봉사활동 그리고 여러 아르를 했습니다. 특히 제가 일하던 회사와 저희 부서는 서로 협력하여 업무를 진행하는 경우가 많았는데 서로 모르는 것이 있을 때마다 서로에게 조언을 해주었고 도움을 받고 나서는 더욱 좋은 결과도 있었습니다. 이러한 경험을 통해 공동체 속에서 업무가 진행함에 있어 서로의 입장을 정확하게 이해함으로써 원만한 커뮤니케이션을 하는데 도움이 되는 의사소통 방법이라 생각하는 대학생활 동안 다양한 경험들을 했습니다. 첫 번째로 어학연수였습니다. 어학연수는 학교 현지인 학생들과의 교류로 이루어졌습

In [ ]:
coverletter_generator('컴퓨터공학 ')

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


tensor([[42000, 15627, 25855,     3]])
0: 컴퓨터공학


1: 컴퓨터공학 그 이후부터는 저의 연구 분야에서 기술을 도입하는 것에 관심을 가지게 되었고 현재에 이르렀습니다. 전자공학을 전공하며 배운 기계공학의 지식은 제가 연구에 더 적합한 인재로 성장하게 해주었으며 이러한 배움을 토대로 더욱 넓은 분야의 기술을 습득하는데 노력하고 있습니다. 이를 바탕으로 전장부품 생산의 경쟁력을 향상시키는 데에 기여하고 싶습니다. 세계 최고의 엔지니어 제가 추구하는 글로벌 엔지니어의 자세는 남들의 눈에 띄는 무언가를 하는 것입니다. 학부 시절 전자회로 실험을 수강하며 회로설계 및 실습지식을 쌓았습니다. 또한 설계 과목에서 교수님께 양해를 구하고 여러 번의 시뮬레이션을 반복하면서 오차가 발생했을 때 원인 분석과 해결방법을 고 민해 봄으로써 오차의 원인을 파악하는 법을 길렀고 이러한 노력 덕분에 전자회로 설계와 해석 과목에서 등라는 성적을 얻을 수 있었습니다. 이를 통해 전자공학 기술의 발전 가능성 을 깨달았고 세계 최고의 전자회사로 발전하겠다는 의 꿈을 품게 되었습니다.


2: 컴퓨터공학.. 새로운 다짐을 하게 된 계기와 이러한 시도의 과정에서 본인이 느낀 점과 단점을 극복하기 위해 했던 행동과 생각 결과에 대해 최대한 구체적으로 작성하여 주십시오. 자 저는 년 월년 월까지 약 개월간 대학교 학생회의 사무부장으로 활동했습니다. 학과에서 주최하는 행사에 여러 기관의 협력을 얻어 수행하기도 하며 행사마다 운영팀별로 필요한 물품이나 행사를 기획하 고 행사마다 필요한 업무를 정리하여 문서를 작성하였습니다. 이러한 업무들은 사무부장이라는 직책에 어울리도록 사무부장으로서 잘 수행하는 것이상으로 느꼈습니다. 또한 부원들의 업무에 차질이 없도록 도움을 주고자 참여율이 저조한 동아리에 따로 연락하거나 학생회비 내역을 공개하고 지출내역을 투명하게 공개하여 모두가 참여하고 즐거운 행사를 만들 수 있었습니다. 저는 학생회의 구성원으로써 책임감과 주인의식을 갖고 업무를

In [ ]:
coverletter_generator('경제 ')

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


tensor([[42000, 14785,     3]])
0: 경제 수출하면서 알게 된 건 자동차에 들어가는 부품으로 철판을 사용한다는 것과 자동차 부품을 조립할 때 사용하는 철판을 직접 만든다는 것입니다. 현대기아차 해외영업 직무에 필요한 인재가 되기 위해서 첫 번째로 무역의 기 본인 것으로 만들기입니다. 먼저 저는 해외 영업 직무를 위해 무역 관련 기초지식과 커뮤니케이션 기술을 습득하였습니다. 특히 국제통상학과 경제학을 통해 얻은 지식을 바탕으로 무역실무론 국제재무론을 모두 수강하여 모든 경영 통찰을 기르는데 집중했습니다. 이를 통해 해외 영업에 필요한 기본적인 지식들을 갖추었습니다. 두 번째로 대인관계와 의사소통 능력을 갖추기 위한 교육을 수료했습니다. 말레이시아에서 인턴으로 근무했을 당시 현지인들과 쉽게 소통하는 법을 배웠습니다. 그들의 관심을 끌기 위해 그들이 좋아하는 게임을 조사하고 인사말하기를 통해 인사했습니다. 또한 한국 설명회를 열어 한국의 전통문화를 알려주었고 말레이시아에서는 한국 음식 만들기 게임을 만들어 한국 음식 체험 이벤트를 열었습니다.


1: 경제 지역사회 발전에 기여한 보람을 느낄 수 있는 업무 현장 에서 일하는 게 가장 중요하다고 생각했고 생산성 향상을 위해 힘쓰는 한국산업단지공단으로 진로를 정하였습니다 아쉬운 점


2: 경제.. 군 복무기간 동안 전공공부를 하며 경제관리에 관심을 가지게 되었습니다. 재무회계 분야에 관심이 많았기에 수업을 통해 지식을 쌓아나갔습니다. 과목을 수강하며 회계와 더불어 부가가치세 원가회계 등의 관련 법규들을 준수하였으며 더 나아가 기업가 정신을 함양하기 위하여 경영학을 부전공하였습니다... 대학교 학년 재학 시절 경영학원론 수업의결 과로 기업의 투자유치의 기초를 배우는 원가회계에 관한 수업을 들었고 기업과 산업 전반의 재무지표를 파악할 수 있는 회계원리 수업을 들었습니다. 수업을 통해 기업의 중장기 전략기획 및 현금흐름 예측 과제를 수행했습니다. 이를 토대로 기업이 투자하고 싶은 시장과 수익구조를 

In [ ]:
coverletter_generator('법학 ')

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


tensor([[42000,  4425,  8580,     3]])
0: 법학 과거 대학교에서는 학년 신입생 때 컴퓨터 네트워크과목을 수강하면서 처음 컴퓨터 소프트웨어공학이라는 학문에 흥미를 느끼게 되었습니다. 그 뒤 선배나 조교들을 찾아다니며 열심히 배우고 복습하였습니다. 배운 내용을 바탕으로 프로젝트도 직접 만들어 보았고 동아리 활동에서도 적극적으로 참여하여 신입생 때와 같은 모습을 보여줌으로써 인정받아왔습니다. 이 경험을 토대로 졸업 후에 컴퓨터공학부의 학년이 되어 처음으로 개발자의 길을 걷게 되었습니다. 대학교에 입학하고 컴퓨터 기초라는 학문을 접했을 뿐만 아니라 개발자의 꿈을 키우기 위해 대학원 진학하였고 석사과정을 밟으면서 연구도 진행하였습니다. 이러한 과정에서 프로그래밍에 대한 재미를 느꼈으며 관련 수업을 많이 수강하였습니다. 개발자는 혼자가 아닌 함께 한다는 것을 느꼈습니다. 혼자서만 개발해서는 원하는 결과물을 얻는 데 한계가 있었으며 개발과 유지보수의 효율성 역시 굉장히 높았습니다. 따라서 혼자서 만드는 것보다 협업을 통해 같이 성장하는 것을 더 좋아해서 대학원 연구실에서 연구보조활동을 하면서 개발을 하는 데에 도움이 되었습니다. 학부 과정 중에는 다양한 프로젝트를 통해서 프로젝트를 진행했으며 이를 바탕으로 특허출원을 하고 한국 정보처리학회에서 교육도 받고 있습니다. 프로젝트를 통해서 배운 기술과 노하우를 다른 분야에서도 활용할 수 있도록 컴퓨터 소프트웨어 과목에서 지속적인 발전을 위해 노력하고 있습니다.


1: 법학 대학 졸업과제를 하기 위해 산업공학과에서 배운 지식을 활용하여 실제로 자동차를 만들어 보기도 하고 기계공학과 사람들과 같이 실기시험을 준비하면서 기계 설계 생산관리에 대해 공부하였습니다. 처음 접해 보는 전공에 대한 지식인 만큼 설계실습 과목 중 가장 어려웠지만 부족한 부분이 많았습니다. 이에 저는 부족한 부분을 채우기 위해 다른 학생들보다 먼저 많은 시간과 노력을 투자하여 노력을 쏟았습니다. 그 결과 학년 평점. 점을 받을 

In [ ]:
coverletter_generator('외국어 ')

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


tensor([[42000, 39016,     3]])
0: 외국어 첫째도 함께 일하려 노력하였습니다. 대학 시절 외국에서 교환학생을 하면서 현지인 친구들과 외국인 친구들 사이에서 소통의 중요성을 깨달았고 이는 영어실력 향상과 어학 실력 향상을 위해 큰 도움이 되었습니다. 대학에서 영어는 필수라고 생각했고 영어에 관심이 있었던 저는 년 넘게 영어를 꾸준히 공부했고 그 결과 토익점수를 달성하였습니다. 이처럼 어학 실력을 향상을 위해 노력했던 경험은 입사 후 업무를 수행함에 있어 큰 도움이 될 것입니다. 둘째 사람을 대하는 태도가 가장 중요하다고 생각합니다. 한 번이라도 실수를 하게 되면 빠르게 문제점을 찾고 해결해야 하기 때문입니다. 군 시절 행정병으로 복무하면서 여명의 훈련병을 지휘하는 역할을 맡았습니다. 훈련병들은 각자 맡은 업무가 있었는데 문제가 생길 때마다 모두 책임져야 했습니다. 그래서 저는 항상 먼저 사과하고 모든 상황에 대해 천천히 설명해 주었습니다. 이렇게 행동하니 훈련병들도 자신의 할 일을 저에게 떠맡기 시작하였고 서로 배려하며 훈련병들을 신뢰하게 되었습니다. 입사 후에도 다른 사람들과 원만한 관계를 유지함으로써 회사 내 구성원으로서의 업무능력을 증진할 수 있을 것이라고 확신합니다.


1: 외국어 학창시절 저는 외국어 학습에 열정을 쏟았습니다. 국제무역상무 무역영어 수업을 통해 영어를 익히고 통역하는 데에 필요한 기말 시험을 보았습니다. 영어 실력뿐만 아니라 언어능력까지도 갖추고 싶었기에 외국어고등학교로 진학하였습니다. 그런데 영어회화 실력이 늘지 않아서 스스로 더 노력해야만 했습니다. 그래서 외국어고등학교를 포기하고 일본어과에 입학했습니다. 하지만 일본어 공부는 계속되었고 결국 년 후에 다시 일본어과에 재입시하였습니다. 일어뿐만 아니라 복수전공하며 한 과목만 수강하는 다른 대학과는 달리 전혀 다른 일본 대학에서 강의를 시작하게 된 점이 더욱 흥미로웠습니다. 또한 해외연수와 일본 문화교류 등의 여러 프로그램을 통하여 일본 사람과의 생활에서 많

In [ ]:
coverletter_generator('4차산업 ')

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


tensor([[42000, 26021, 16078,     3]])
0: 4차산업 저는 학창시절 때부터 차 산업혁명에 관심이 있었습니다. 이러한 관심을 바탕으로 대학교 학년 때 소프트웨어 개발공학이라는 전공과목을 수강하였습니다. 이 수업을 통해서 제가 개발한 알고리즘이 누군가에게 도움이 되는 것을 볼 수 있었고 개발자로서 필요한 역량을 갖추게 되었습니다. 또한 인공지능 기술을 통해 차산업혁명에 발맞춰가는 것에 저의 도전정신이 큰 가치를 가져다 줄 것이라 생각하였습니다.


1: 4차산업 소비자들과 소통하는 가 되고 싶습니다 자동차는 인간의 삶을 더욱 편리하게 만드는 중추적인 역할을 하고 있습니다 많은 기업이 이 분야를 소홀히 합니다 저는 자동차가 더 편리하도록 소비자와의 소통에 힘쓰고 싶습니다 이 중에서도 소비자와 소통하여 자동차 부품의 품질을 향상시키는 것이 시장 경쟁력을 유지하는 중요한 열쇠라고 생각했습니다 아쉬운 점 현대사회에서 소비자들은 자동차를 단순히 타고 다니는 수단이 아닌 삶의 일부로 보고 자동차를 통해 더 나은 삶의 모습을 만들어 갑니다 현대사회에서 소비자들은 자신의 삶과 사회의 가치를 우선시하며 살아왔으며 이는 현대자동차의 전폭적인 연구개발과 브랜드 가치 때문입니다 또한 많은 국내 완성차 회사들이 고객들에게 더 많은 경험을 제공하고 다양한 문화를 이해하고 있다고 생각합니다 아쉬운 점 따라서 현대자동차는 소비자의 니즈를 파악하고 이를 만족시켜 줄 수 있는 자동차를 생산 유통하고 소비자를 위해 최상의 차량을 제공하기 위해 노력하고 있습니다 이러한 노력들은 현대 자동차가 소비자의 신뢰를 얻는 데 큰 도움이 될 것이라 확신합니다 저는 자동차 구매의 기 본인 공제회 경영지원팀 사원으로서 차량 평가업무를 수행하며 기업의 이익을 극대화시키기 위한 재무적 지원과 재무건전성을 확보하기 위한 회계 및 세무지식을 쌓았고 이를 바탕으로 현대 자동차의 자동차 부품 가격을 분석하고 수익성 향상을 위해 노력하는 현대 자동차의 인재로 성장하겠습니다


2: 4차산업 소비

In [ ]:
coverletter_generator('어떤 어려운 상황에서도')

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


tensor([[42000, 14247, 15901, 40153,     3]])
0: 어떤 어려운 상황에서도 그 당시 현장에 필요한 물품들을 인터넷과 전공 서적을 통해 직접 구매하고 현장에서 조립하여 완성시킨 경험이 있습니다. 학년이 되어서야 전기과 선배들의 도움을 받으며 실습을 시작하였습니다. 실습생으로 실습에 참여하여 설비와 부품에 결선이 되는 회로를 보고 배선도를 보면서 기기의 위치 선정 등을 하여 현장이 원활하게 가동될 수 있도록 유지보수하는 업무를 맡게 되었습니다. 직접 배선하면서 회로뿐만 아니라 부품에 대한 안목도 키울 수 있었으며 전선의 작동방식까지 배울 수 있었습니다. 이러한 경험은 앞으로의 회사생활에 큰 도움이 될 것입니다. 또한 교내 캡스톤 디자인과목에서 제품을 개선하고자 하였습니다. 브레인스토밍을 통하여 원하는 조건에 따른 제품 제작이 가능한지 확인하고 이를 설계해 제품의 완성도를 높이는 프로젝트였습니다. 저희는 그 과정을 통하여 새로운 제품이 나왔을 때 가장 성취감을 느낄 것으로 생각하였으며 그 과정이 값진 것이라 느꼈습니다. 그래서 저는 팀원들과 각자 역할을 정해 프로젝트를 진행하였습니다. 그리고 브레인스토밍에서 제품을 효율적으로 제작하기 위한 방법론을 찾아보았고 팀장을 맡아 다양한 제품을 개발하였고 각 팀원의 능력에 맞게 일을 배분하여 진행하였습니다. 이렇게 다양한 팀 활동을 하면서 의사소통 능력을 키웠고 문제를 해결해 나가는 방법 과 문제 해결 능력을 기를 수 있었습니다.


1: 어떤 어려운 상황에서도. 고등학교 학년 때 친구들과 전국 규모 축제를 주최한 적이 있습니다. 그 당시 저는 학생회 임원으로서 예산기획 업무를 담당하며 축제 준비와 예산안 작성을 총괄한 경험이 있습니다. 저는 한 달간 예산기획 업무를 담당했습니다. 당시 제가 맡은 업무는 지역축제 중 하나인 과년도 행사를 기획하는 것이었습니다. 예산에 맞춰 가장 많은 매출을 올릴 수 있는 주점을 찾는 것과 행사 첫날 주점에서 판매하여 수익을 올릴 방법을 강구해야 했습니다. 

In [ ]:
coverletter_generator('빅데이터 ')

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


tensor([[42000, 38809,     3]])
0: 빅데이터 긴장감이 풀리면서 팀원 모두 만족감을 느꼈습니다. 이러한 책임감으로 인해 프로젝트를 무사히 수행할 수 있었습니다. 그리고 이런 도전정신이 저를 움직이게 하는 원동력입니다. 대학 시절 제 인생의 키워드는 내가 가장 잘할 수 있는 일이었습니다. 제가 가장 잘할 수 있 는 일을 하기 위해 노력하였고 가장 잘하고 싶은 일은 컴퓨터 직무였습니다. 그래서 자연스레 직무에 관심 갖게 되었고 직무가 바로 제가 잘할 수 있을 것이라는 확신을 하게 되었습니다. 그래서 학년 때부터는 컴퓨터 프로그래밍 동아리 활동을 시작했습니다. 처음 가입했을 때는 운영진 회원들과 협업하느라 동아리 운영에 어려움을 겪었고 동아리 활동만으로는 한계가 있다는 것을 깨닫게 되었습니다. 저는 교내 기초 프로그래밍 학술동아리에 가입하여 프로그래밍에 관해 배우고 세미나를 찾아다니며 많은 선배님들과 만남을 가졌습니다. 또한 전공 공부와 병행하며 자격증에 도전하고 있습니다. 이러한 끊임없는 도전으로 현재 전국 개대학에서 여개의 멘토님들에게 수업을 하고 있습니다. 동아리 활동 외에도 동아리 사람들과 스터디그룹을 꾸려 동아리 생활을 같이하고 있습니다. 저의 이호 열정은 롯데정보통신이 업계 최고의 회사로 성장하는 원동력이 될 것입니다.


1: 빅데이터. 정황과는 상관없는 과정으로 진행됩니다. 다른 사람들과 함 께 협력하는 관계라고 하면 보통 긍정적인 시각을 떠올립니 다. 저는 이 생각을 비협조적이고 비주류적인 사람과 협업하여 성과를 도출해냈습니다. 대학교 때 한 가지 프로젝트를 진행했습니다. 인공지능을 활용하여 알고리즘에 관한 부분을 기획했습니다. 하지만 팀원들의 협조와 여러 방면으로 어려움을 겪었습니다. 결국 모두 참여하지 않았고 뒤처졌습니다. 이를 해결하기 위해 먼저 팀원을 찾아갔습니다. 그리고 프로젝트에 관심이 있는 사람들이 어떤 역할을 하는지 조사하였습니다. 그 결과 비협조적이며 비판적인 사람도 있었습니다. 저와 마찬가지로 부정적인 의견

In [ ]:
coverletter_generator('공무원 ')

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


tensor([[42000, 21476,     3]])
0: 공무원 공직시장에서 일 하시는 분들을 도와 민원인을 상대하며 알게 된 것입니다. 한 번은 공무원 공단 내 시청 직원들을 위해 퇴직연금 사업을 운영한다는 공고를 보게 되었습니다. 타 공단은 퇴직연금 지급과 관련하여 고객 근로자들의 권리를 위배하고 있고 공무원 공단에 대한 이미지 또한 실추하고 있었습니다. 특히 퇴직연금 지급이 불가하다는 판 단을 접한 적이 있었기 때문에 더욱 의욕을 가지고 공단을 방문하였습니다. 저는 이러한 문제를 해결하기 위하여 공단의 모든 사업과 관련된 문서들을 찾아보았습니다. 그 중 퇴직연금의 유형과 가입요건 등을 알아보았고 국가유공자 전용 퇴직연금제도는 월일제 도입니다. 이는 노인장기요양등급 산정에 대한 기준으로 근로자의 복지에 직접적인 도움을 주고 있음을 의미하는 것이며 추후 고용안정을 제고할 수 있는 이점이 있다는 것을 알 수 있습니다. 공단에 방문하는 많은 시민분들에게 공단 관련 정보를 알려드린 결과 공단 관련 담당자로부터 긍정적인 답변을 받을 수 있었습니다. 해당 공고를 보고 난 후부터는 제가 직접 해당 사업에 종사하시는 공무원분들까지 찾아 뵈어 공단이 가지고 있는 서비스와 민원을 해결하는 방법에 대하여 여러 의견을 나누는 시간을 가지기도 하였습니다. 또한 공단에서 제공하는 자료를 수집하여 이를 정리하여 공단 직원분들에 게 나눠주었고 공단 내에 있는 민원인들에게도 전달하였습니다. 이러한 과정을 통하여 저는 상대방에게 나의 의견을 주장하는 것이 아닌 다른 사람들의 의견에도 귀를 기울이는 열린 태도를 갖게 되었고 상호 존중하는 태도로 업무에 임할 수 있었습니다.


1: 공무원 공직시장에서의 개선 방안은 국민의 알권리 향상이라는 목표를 가장 첫 번째로 설정하였고 이를 달성하기 위하여 업무 처리 규정을 직접 만들고 수정하면서 저의 능력을 향상시키기 위해 노력했습니다. 저는 인턴으로 근무할 당시 퇴근 후 바로팩토리에 자재 입고 및 적기 납품을 위한 생산기술팀에서 품질관리 업무를